### ISSUE TITLE
[Bug] Octoprint Widget showing completion % error

### ISSUE THREAD

**Issue by asad-albadi** [gethomepage/homepage#2245]
### Description

Currently Homepage widget for Octoprint shows the following 

![image](https://github.com/gethomepage/homepage/assets/27831793/5e1c6148-6b55-40f7-8420-0585c75b7a2b)

`
Something went wrong.
TypeError: Cannot read properties of undefined (reading 'completion')

    at l (http://10.10.12.57:3003/_next/static/chunks/8975.6a5e880df98cb909.js:1:1145)
    at h (http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:35344)
    at n (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:15374)
    at L (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:28855)
    at div
    at li
    at q (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:31545)
    at ul
    at J (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:35301)
    at div
    at http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:44035
    at div
    at l (http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:70166)
    at http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:62780
    at http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:61725
    at l (http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:70166)
    at http://10.10.12.57:3003/_next/static/chunks/6133-1abb682bd7f256a6.js:1:41981
    at div
    at W (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:35696)
    at div
    at div
    at he (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:53112)
    at n (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:15374)
    at http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:90174
    at ue (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:51118)
    at div
    at div
    at div
    at be (http://10.10.12.57:3003/_next/static/chunks/pages/index-62d3754e96f28eb6.js:1:60469)
    at u (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:14817)
    at s (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:14609)
    at a (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:16243)
    at a (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:15886)
    at s (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:16802)
    at u (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:15314)
    at http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:90174
    at http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:13875
    at l (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:1471)
    at n (http://10.10.12.57:3003/_next/static/chunks/pages/_app-9363fc24f9e34742.js:1:6048)
    at r (http://10.10.12.57:3003/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (http://10.10.12.57:3003/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (http://10.10.12.57:3003/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)
`

### Steps to reproduce

let a print progress to above 1%

if the printer is offline > no issue, widget shows correctly
if the printer is online, not printing > no issue, widget shows correctly
if the printer is online and printing, below 1% > o issue, widget shows correctly
if the printer is online and printing, above or equal 1% > the  issue starts, widget shows the mentioned error

### homepage version

v0.7.4 (8ec488e, Oct 18, 2023)

### Octoprint version 
OctoPrint 1.9.3 Python 3.10.13

### Installation method

Docker

### Troubleshooting

- Lab:
    - OctoPrint:
        icon: https://octoprint.org/assets/img/logo.png
        href: http://10.10.12.53:5000
        description: 3D Printer Controller.
        widget:
            type: octoprint
            url: http://10.10.12.53:5000
            key: apikey

### Other
/api/job
`{
  "job": {
    "averagePrintTime": null,
    "estimatedPrintTime": null,
    "filament": null,
    "file": {
      "date": 1698384686,
      "display": "CE3E3V2_how_new_bookend.gcode",
      "name": "CE3E3V2_how_new_bookend.gcode",
      "origin": "local",
      "path": "CE3E3V2_how_new_bookend.gcode",
      "size": 3831743
    },
    "lastPrintTime": null,
    "user": "asad"
  },
  "progress": {
    "completion": 87.81859848116117,
    "filepos": 3364983,
    "printTime": 30694,
    "printTimeLeft": 4257,
    "printTimeLeftOrigin": "estimate"
  },
  "state": "Printing"
}`
/api/printer
`
└─$/bin/python3 /home/asad/Projects/octoprint_api_python_script/1.py
{
  "sd": {
    "ready": true
  },
  "state": {
    "error": "",
    "flags": {
      "cancelling": false,
      "closedOrError": false,
      "error": false,
      "finishing": false,
      "operational": true,
      "paused": false,
      "pausing": false,
      "printing": true,
      "ready": false,
      "resuming": false,
      "sdReady": true
    },
    "text": "Printing"
  },
  "temperature": {
    "W": {
      "actual": 0.0,
      "offset": 0,
      "target": null
    },
    "bed": {
      "actual": 59.93,
      "offset": 0,
      "target": 60.0
    },
    "tool0": {
      "actual": 208.12,
      "offset": 0,
      "target": 206.0
    }
  }
}
`
### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by calvinbui** [comment]
same for me on OctoPrint 1.9.3

**Comment by asad-albadi** [comment]
> same for me on OctoPrint 1.9.3, but only during a print.

yes same version for me as well OctoPrint 1.9.3
Python 3.10.13

**Comment by shamoon** [comment]
The reason the template asks for things is because we can’t do anything without it. Please post the output from the api, I don’t have a 3d printer. Their release notes don’t mention anything breaking for 1.9.3

@williamwoldum
@batuhan0sanli

**Comment by asad-albadi** [comment]
> The reason the template asks for things is because we can’t do anything without it. Please post the output from the api, I don’t have a 3d printer. Their release notes don’t mention anything breaking for 1.9.3
> 
> @williamwoldum @batuhan0sanli

`
{
  "job": {
    "averagePrintTime": null,
    "estimatedPrintTime": null,
    "filament": null,
    "file": {
      "date": 1698384686,
      "display": "CE3E3V2_how_new_bookend.gcode",
      "name": "CE3E3V2_how_new_bookend.gcode",
      "origin": "local",
      "path": "CE3E3V2_how_new_bookend.gcode",
      "size": 3831743
    },
    "lastPrintTime": null,
    "user": "asad"
  },
  "progress": {
    "completion": 87.81859848116117,
    "filepos": 3364983,
    "printTime": 30694,
    "printTimeLeft": 4257,
    "printTimeLeftOrigin": "estimate"
  },
  "state": "Printing"
}
`

**Comment by shamoon** [comment]
Assuming thats `/api/job`, whats `/api/printer`?

**Comment by asad-albadi** [comment]
> Assuming thats `/api/job`, whats `/api/printer`?

yes, that's api/job

this is api/printer

`
└─$/bin/python3 /home/asad/Projects/octoprint_api_python_script/1.py
{
  "sd": {
    "ready": true
  },
  "state": {
    "error": "",
    "flags": {
      "cancelling": false,
      "closedOrError": false,
      "error": false,
      "finishing": false,
      "operational": true,
      "paused": false,
      "pausing": false,
      "printing": true,
      "ready": false,
      "resuming": false,
      "sdReady": true
    },
    "text": "Printing"
  },
  "temperature": {
    "W": {
      "actual": 0.0,
      "offset": 0,
      "target": null
    },
    "bed": {
      "actual": 59.93,
      "offset": 0,
      "target": 60.0
    },
    "tool0": {
      "actual": 208.12,
      "offset": 0,
      "target": 206.0
    }
  }
}
`

**Comment by batuhan0sanli** [comment]
I noticed the same issue today when trying to print. I'm waiting for a long print to finish, and I'll look into it afterward.

**Comment by shamoon** [comment]
Using the data you supplied (thanks) works fine but I suppose if progress is empty this can happen

<img width="385" alt="Screenshot 2023-10-27 at 8 00 29 AM" src="https://github.com/gethomepage/homepage/assets/4887959/a7cf13fd-2ee4-478a-aecc-8a81e13860a6">
