### ISSUE TITLE
[Bug] Getting TypeError: Cannot read properties of undefined (reading 'inactive_file') when showing stats on podman

### ISSUE THREAD

**Issue by idelsink** [gethomepage/homepage#2271]
### Description

I'm running homepage in a rootless podman container on a Fedora 38 host with the podman socket mounted. When I open the container stats menu, I get the following error:

> TypeError: Cannot read properties of undefined (reading 'inactive_file') 

![image](https://github.com/gethomepage/homepage/assets/8396902/7beaaaad-9bc2-4ca8-b52e-e91bb907e0a5)

[Screencast from 2023-11-03 16-58-45.webm](https://github.com/gethomepage/homepage/assets/8396902/7fe843bc-0d2d-4d36-9a8b-cdc46d62e42a)

### Steps to reproduce

The following versions are being used:

```sh
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 38 (Thirty Eight)
Release:        38
Codename:       ThirtyEight

$ podman version
Client:       Podman Engine
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.20.8
Built:        Wed Sep 27 20:24:38 2023
OS/Arch:      linux/amd64
```

Make sure that the rootless podman socket is started

1. Start the Podman daemon providing the socket `systemctl --user start podman.socket`
2. Start the homepage container
    ```sh
    $ podman run --rm -it \
        --name homepage \
        -p 8080:3000 \
        -v "${XDG_RUNTIME_DIR}/podman/podman.sock:/run/podman/podman.sock" \
        --security-opt "label=disable" \
        -v homepage:/app/config \
        --label "homepage.group=Test group" \
        --label "homepage.name=Homepage" \
        --label "homepage.icon=homepage.png" \
        ghcr.io/gethomepage/homepage:latest
    ```
3. Update the docker.yaml file to add the podman socket:
    ```sh
    $ podman exec -it homepage \
         sh -c "printf 'socket:\n  socket: /run/podman/podman.sock\n' >> /app/config/docker.yaml"
    ```
4. Open the webpage http://localhost:8080
5. Click the stats button of the homepage container

### homepage version

v0.7.4 (8ec488e, Oct 18, 2023)

### Installation method

Other (please describe above)

### Configuration

```yaml
# docker.yaml
---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock
socket:
  socket: /run/podman/podman.sock
```

### Container Logs

n/a

### Browser Logs

<details>
  <summary>Browser logs</summary>
 
```txt
framework-eda4609282c049ac.js:1 TypeError: Cannot read properties of undefined (reading 'inactive_file')
    at o (index-9fca8f5abfd41967.js:1:62145)
    at d (index-9fca8f5abfd41967.js:1:63439)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
du @ framework-eda4609282c049ac.js:1
a.componentDidCatch.t.callback @ framework-eda4609282c049ac.js:1
Ua @ framework-eda4609282c049ac.js:1
ki @ framework-eda4609282c049ac.js:1
bi @ framework-eda4609282c049ac.js:1
yi @ framework-eda4609282c049ac.js:1
(anonymous) @ framework-eda4609282c049ac.js:1
ws @ framework-eda4609282c049ac.js:1
ls @ framework-eda4609282c049ac.js:1
S @ framework-eda4609282c049ac.js:1
T @ framework-eda4609282c049ac.js:1
index-9fca8f5abfd41967.js:1 TypeError: Cannot read properties of undefined (reading 'inactive_file')
    at o (index-9fca8f5abfd41967.js:1:62145)
    at d (index-9fca8f5abfd41967.js:1:63439)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494) {componentStack: '\n    at d (http://localhost:8080/_next/static/chun…t/static/chunks/main-5004eaa7b9f962cb.js:1:11878)'}
value @ index-9fca8f5abfd41967.js:1
a.componentDidCatch.t.callback @ framework-eda4609282c049ac.js:1
Ua @ framework-eda4609282c049ac.js:1
ki @ framework-eda4609282c049ac.js:1
bi @ framework-eda4609282c049ac.js:1
yi @ framework-eda4609282c049ac.js:1
(anonymous) @ framework-eda4609282c049ac.js:1
ws @ framework-eda4609282c049ac.js:1
ls @ framework-eda4609282c049ac.js:1
S @ framework-eda4609282c049ac.js:1
T @ framework-eda4609282c049ac.js:1
localhost/:1 The resource http://localhost:8080/api/config/custom.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```
</details>

### Troubleshooting

n/a

### Other

It seems that the `memory_stats` that are returned by podman's rest API does not contain the `stats` object as used in 

https://github.com/gethomepage/homepage/blob/ebd384c62dcff0e0ec4b27097f4b9baee83a0bdb/src/widgets/docker/stats-helpers.js#L16

Simply changing this to the following fixes it.

```js
stats.memory_stats.usage - (stats.memory_stats.total_inactive_file ?? stats.memory_stats.stats?.inactive_file ?? 0)
```

I can make a PR if requested! :smile: 

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Thanks for the detailed explanation, yes feel free to PR that 1-liner

**Comment by idelsink** [comment]
I've created the PR :tada:
