### ISSUE TITLE
[Bug] 500 Errors on many services since 0.8.0 update

### ISSUE THREAD

**Issue by joshoram80** [gethomepage/homepage#2288]
### Description

Almost all of my widgets that access an API to display information are broken in 0.8.0 but were all working fine in 0.7.4. I have changed nothing since the update to my configuration

### Steps to reproduce

1) Run homepage with exact setup as 0.7.4
2) Most homepage widgets have API errors

### homepage version

v0.8.0 (b019295, Nov 9, 2023)

### Installation method

Docker

### Configuration

```yaml
labels:
      - homepage.group=Media Management
      - homepage.name=Sonarr
      - homepage.icon=sonarr.png
      - homepage.href=http://sonarr.my.domain
      - homepage.description=Sonarr
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr.my.domain
      - homepage.widget.key=$SONARR_API_KEY
      - homepage.widget.enableQueue=true
```

### Container Logs

```
11/09/2023
06:25:11 PM
[2023-11-09T07:25:11.819Z] error: <httpProxy> Error calling http://sonarr.my.domain/api/v3/queue...
11/09/2023
06:25:11 PM
[2023-11-09T07:25:11.820Z] error: <httpProxy> [
11/09/2023
06:25:11 PM
  500,
11/09/2023
06:25:11 PM
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
11/09/2023
06:25:11 PM
      at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:462:24)
11/09/2023
06:25:11 PM
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
11/09/2023
06:25:11 PM
      ... 3 lines matching cause stack trace ...
11/09/2023
06:25:11 PM
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
11/09/2023
06:25:11 PM
      at Socket.socketOnData (node:_http_client:541:22)
11/09/2023
06:25:11 PM
      at Socket.emit (node:events:517:28)
11/09/2023
06:25:11 PM
      at addChunk (node:internal/streams/readable:335:12)
11/09/2023
06:25:11 PM
      at readableAddChunk (node:internal/streams/readable:308:9) {
11/09/2023
06:25:11 PM
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
11/09/2023
06:25:11 PM
        at new NodeError (node:internal/errors:405:5)
11/09/2023
06:25:11 PM
        at new ClientRequest (node:_http_client:188:11)
11/09/2023
06:25:11 PM
        at Object.request (node:https:358:10)
11/09/2023
06:25:11 PM
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:284:24)
11/09/2023
06:25:11 PM
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:459:10)
11/09/2023
06:25:11 PM
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
11/09/2023
06:25:11 PM
        at Object.onceWrapper (node:events:632:26)
11/09/2023
06:25:11 PM
        at ClientRequest.emit (node:events:517:28)
11/09/2023
06:25:11 PM
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
11/09/2023
06:25:11 PM
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
11/09/2023
06:25:11 PM
      code: 'ERR_INVALID_PROTOCOL'
11/09/2023
06:25:11 PM
    },
11/09/2023
06:25:11 PM
    code: 'ERR_FR_REDIRECTION_FAILURE'
11/09/2023
06:25:11 PM
  }
11/09/2023
06:25:11 PM
]
```

### Browser Logs

Failed to load resource: the server responded with a status of 500 ()

### Troubleshooting

```
/app # ping sonarr.my.domain
PING sonarr.my.domain (192.168.0.10): 56 data bytes
64 bytes from 192.168.0.10: seq=0 ttl=64 time=0.030 ms
64 bytes from 192.168.0.10: seq=1 ttl=64 time=0.087 ms
64 bytes from 192.168.0.10: seq=2 ttl=64 time=0.053 ms
64 bytes from 192.168.0.10: seq=3 ttl=64 time=0.064 ms
```

/app # curl -L -k 'http://sonarr.my.domain/api/v3/queue?apikey=xxxxxxxxxxxxxxxxxxxxxxxxxx'
{
  "page": 1,
  "pageSize": 10,
  "sortKey": "timeleft",
  "sortDirection": "descending",
  "totalRecords": 0,
  "records": []

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Have you tried re-creating your container? Theres nothing in 0.8.0 that would explain this nor can I reproduce it.

**Comment by shamoon** [comment]
Oh, maybe this https://github.com/gethomepage/homepage/pull/2214/files

**Comment by shamoon** [comment]
What if you change the protocol to https ?

**Comment by joshoram80** [comment]
Yes changing to https in the docker labels works now.
