### ISSUE TITLE
[Bug] Cannot read properties of undefined (reading 'code')

### ISSUE THREAD

**Issue by Drynael** [gethomepage/homepage#2418]
### Description

`Something went wrong.
TypeError: Cannot read properties of undefined (reading 'code')

    at w (https://start.local/_next/static/chunks/8185.2267ed13f79fe630.js:1:3018)
    at $ (https://start.local/_next/static/chunks/8185.2267ed13f79fe630.js:1:3946)
    at h (https://start.local/_next/static/chunks/6133-1abb682bd7f256a6.js:1:35344)
    at n (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)
    at Q (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:44612)
    at div
    at div
    at div
    at div
    at he (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:54675)
    at n (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)
    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588
    at fe (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:52681)
    at div
    at div
    at div
    at pe (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:62156)
    at a (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15657)
    at a (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15300)
    at s (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:16216)
    at u (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:14728)
    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588
    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:13979
    at l (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:1471)
    at n (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:6048)
    at r (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)`

### Steps to reproduce

Load or Refresh site.

### homepage version

v0.8.2 (a3fcc3e, Nov 25, 2023)

### Installation method

Docker

### Configuration

```yaml
Widgets:
Proxmox
Docker
PhotoPrism
Nextcloud
OPN-Sense
Unifi
Scunity
```

### Browser Logs

framework-eda4609282c049ac.js:1 TypeError: Cannot read properties of undefined (reading 'code')
    at w (8185.2267ed13f79fe630.js:1:3538)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
    at S (framework-eda4609282c049ac.js:1:138467)
du @ framework-eda4609282c049ac.js:1
a.componentDidCatch.t.callback @ framework-eda4609282c049ac.js:1
Ua @ framework-eda4609282c049ac.js:1
ki @ framework-eda4609282c049ac.js:1
bi @ framework-eda4609282c049ac.js:1
yi @ framework-eda4609282c049ac.js:1
(anonymous) @ framework-eda4609282c049ac.js:1
ws @ framework-eda4609282c049ac.js:1
ls @ framework-eda4609282c049ac.js:1
S @ framework-eda4609282c049ac.js:1
T @ framework-eda4609282c049ac.js:1
index-d5b31e72408b9b32.js:1 TypeError: Cannot read properties of undefined (reading 'code')
    at w (8185.2267ed13f79fe630.js:1:3538)
    at Eo (framework-eda4609282c049ac.js:1:63196)
    at Pu (framework-eda4609282c049ac.js:1:74884)
    at xi (framework-eda4609282c049ac.js:1:121319)
    at bs (framework-eda4609282c049ac.js:1:109372)
    at gs (framework-eda4609282c049ac.js:1:109300)
    at vs (framework-eda4609282c049ac.js:1:109163)
    at as (framework-eda4609282c049ac.js:1:105943)
    at ls (framework-eda4609282c049ac.js:1:104494)
    at S (framework-eda4609282c049ac.js:1:138467) {componentStack: '\n    at w (https://start.local/_next/static/ch…t/static/chunks/main-5004eaa7b9f962cb.js:1:11878)'}componentStack: "\n    at w (https://start.local/_next/static/chunks/8185.2267ed13f79fe630.js:1:3018)\n    at $ (https://start.local/_next/static/chunks/8185.2267ed13f79fe630.js:1:3946)\n    at h (https://start.local/_next/static/chunks/6133-1abb682bd7f256a6.js:1:35344)\n    at n (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)\n    at Q (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:44612)\n    at div\n    at div\n    at div\n    at div\n    at he (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:54675)\n    at n (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)\n    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588\n    at fe (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:52681)\n    at div\n    at div\n    at div\n    at pe (https://start.local/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:62156)\n    at a (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15657)\n    at a (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15300)\n    at s (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:16216)\n    at u (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:14728)\n    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588\n    at https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:13979\n    at l (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:1471)\n    at n (https://start.local/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:6048)\n    at r (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)\n    at Y (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)\n    at ie (https://start.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)"[[Prototype]]: Objectconstructor: ƒ Object()assign: ƒ assign()length: 2name: "assign"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]create: ƒ create()defineProperties: ƒ defineProperties()length: 2name: "defineProperties"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]defineProperty: ƒ defineProperty()length: 3name: "defineProperty"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]entries: ƒ entries()length: 1name: "entries"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]freeze: ƒ freeze()length: 1name: "freeze"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]fromEntries: ƒ fromEntries()getOwnPropertyDescriptor: ƒ getOwnPropertyDescriptor()getOwnPropertyDescriptors: ƒ getOwnPropertyDescriptors()length: 1name: "getOwnPropertyDescriptors"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]getOwnPropertyNames: ƒ getOwnPropertyNames()getOwnPropertySymbols: ƒ getOwnPropertySymbols()getPrototypeOf: ƒ getPrototypeOf()groupBy: ƒ groupBy()hasOwn: ƒ hasOwn()is: ƒ is()isExtensible: ƒ isExtensible()isFrozen: ƒ isFrozen()isSealed: ƒ isSealed()keys: ƒ keys()length: 1name: "Object"preventExtensions: ƒ preventExtensions()prototype: {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}seal: ƒ seal()setPrototypeOf: ƒ setPrototypeOf()values: ƒ values()arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]hasOwnProperty: ƒ hasOwnProperty()length: 1name: "hasOwnProperty"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]isPrototypeOf: ƒ isPrototypeOf()length: 1name: "isPrototypeOf"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()length: 0name: "toString"arguments: (...)caller: (...)[[Prototype]]: ƒ ()[[Scopes]]: Scopes[0]valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
value @ index-d5b31e72408b9b32.js:1
a.componentDidCatch.t.callback @ framework-eda4609282c049ac.js:1
Ua @ framework-eda4609282c049ac.js:1
ki @ framework-eda4609282c049ac.js:1
bi @ framework-eda4609282c049ac.js:1
yi @ framework-eda4609282c049ac.js:1
(anonymous) @ framework-eda4609282c049ac.js:1
ws @ framework-eda4609282c049ac.js:1
ls @ framework-eda4609282c049ac.js:1
S @ framework-eda4609282c049ac.js:1
T @ framework-eda4609282c049ac.js:1
start.local/:1 The resource https://start.local/api/config/custom.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
start.local/:1 The resource https://start.local/api/config/custom.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Troubleshooting

n/a

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I don’t think the software is broken, no one else is reporting this. And there’s nothing really actionable here at the moment. Perhaps there’s an error in your config or one of the widgets, we would need something to narrow it down eg emptying the config and adding things one at a time

**Comment by zhyph** [comment]
Same thing started happening to me, in my case I think this happens because of this [line](https://github.com/gethomepage/homepage/blob/04ae39e144ab7f8b1eda67b6dfa7a4da742690f9/src/components/widgets/weather/weather.jsx#L37), this endpoint: `api/widgets/weather?lang=en&latitude=XX.XX&longitude=XX.XX&index=3&label=X&units=metric&apiKey=X&cache=5&style=%5Bobject+Object%5D` started returning an empty `current` object, like so:
```
{
    "location": {
        "name": "Wrong",
        "region": "Wrong",
        "country": "Wrong",
        "lat": XX.XX,
        "lon": XX.XX,
        "tz_id": "Wrong/Wrong",
        "localtime_epoch": XX,
        "localtime": "2023-12-02 22:28"
    },
    "current": {}
}
```
Maybe in my specific case the weather api is returning an incorrect data, but I'm not sure why, it just started spurting out wrong info and breaking the widget on homepage.

**Comment by shamoon** [comment]
hmm maybe the weather api is down or something but yea we didn’t change anything

which weather widget and what’s the config?

**Comment by zhyph** [comment]
Basically the default from the website (weatherapi):
```
- weatherapi:
    label: label
    latitude: xx
    longitude: xx
    units: metric
    apiKey: xx
    cache: 5
```
And I've checked by doing a direct API call, looks like they are not returning the current temperature, that it was supposed to be in the `current` obj

**Comment by Drynael** [comment]
> hmm maybe the weather api is down or something but yea we didn’t change anything
> 
> which weather widget and what’s the config?

Yes it´s the WeatherAPI

i disabled the widget andthe error ist gone.

**Comment by shamoon** [comment]
Well I cant even test it because I dont pay for it, btw openweathermap is totally free

If someone wants to send me their key I can look at it, e.g. on discord `shamoon_dev`

**Comment by shamoon** [comment]
Sorry I meant openmeteo

**Comment by shamoon** [comment]
Theres a free trial, once its over thats it

**Comment by shamoon** [comment]
Also, we have this note about this one in the docs:

> Note: this widget is considered 'deprecated' since there is no longer a free Weather API tier for new members. See the openmeteo or openweathermap widgets for alternatives.

So, we'll see if they pushed some kind of breaking change, but yea, I think the answer is "use something else"

**Comment by Goz3rr** [comment]
Their pricing page still says there's a free tier: https://www.weatherapi.com/pricing.aspx

**Comment by Drynael** [comment]
I still have the Free Plan on weatherapi.com. 
`Note: this widget is considered 'deprecated' since there is no longer a free Weather API tier for new members. See the openmeteo or openweathermap widgets for alternatives.`

I will move to one of those instead.

**Comment by shamoon** [comment]
It's basically bait-and-switch BS. Maybe you guys are grabdfathered in but this is what I see:

<img width="238" alt="Screenshot 2023-12-02 at 12 04 14 PM" src="https://github.com/gethomepage/homepage/assets/4887959/be468150-8dd9-49f4-90ef-3b4997cc9027">

Im sure I could but also I dont really feel inclined to support them with these kind of lame practices.

**Comment by zhyph** [comment]
I've been using that for some time now, +1 month, I did get an e-mail about the end of the free-tier stuff about a week ago, just shrug it off, but it could be that.

**Comment by Goz3rr** [comment]
Strange, this is what I see (even in incognito):

![image](https://github.com/gethomepage/homepage/assets/761433/163e18aa-b5a4-47ab-bd8d-a9efac224eff)

clicking on it leads to https://www.weatherapi.com/signup.aspx which shows:
![image](https://github.com/gethomepage/homepage/assets/761433/9a706eb6-c1df-4dfc-91f9-1f0b6f5ab582)

**Comment by shamoon** [comment]
Well this is my "free plan" 🤨

<img width="559" alt="Screenshot 2023-12-02 at 12 07 42 PM" src="https://github.com/gethomepage/homepage/assets/4887959/f70d9e9c-2744-4867-a46a-3d1ae4969ac8">

That screenshot is the homepage, mine is logged into my account.

Anyway, I wrote to them, but the above still stands, there are better, free-er options

**Comment by shamoon** [comment]
Well, got a key (signed up for a new free trial), still cant repro:

```
- weatherapi:
    label: Testing
    longitude: -118.25896
    latitude: 34.19065
    units: metric
    apiKey: 4adc292c3ae44328b45201048230212
    cache: 5
```

<img width="184" alt="Screenshot 2023-12-02 at 12 12 42 PM" src="https://github.com/gethomepage/homepage/assets/4887959/a1cb9f26-1046-43cb-912d-ba76aec16264">

**Comment by shamoon** [comment]
Maybe it depends on location, someone can post their lat / long that causes this

**Comment by shamoon** [comment]
> With my current API Key, any lat/long were returning an empty object, so I would say that they did something to stop the "old" accounts from using the free tier altogether, it can't be just coincidence lol

Sounds like even more reason to ditch them, grimy that it doesn’t just eg throw a 403

**Comment by Drynael** [comment]
> With my current API Key, any lat/long were returning an empty object, so I would say that they did something to stop the "old" accounts from using the free tier altogether, it can't be just coincidence lol

You were on the right path!
I did regenerate my "old" API Key and now it works again.

**Comment by Goz3rr** [comment]
FWIW mine started working again without having to regenerate API keys or starting a new free trial
