### ISSUE TITLE
[Bug] Moonraker Widget Gives Error

### ISSUE THREAD

**Issue by slamanna212** [gethomepage/homepage#2465]
### Description

When enabling the Moonraker Widget, i get the following error where the widget info should be. It is below. Browsing to the URL manually shows information as normal. 

```
Something went wrong.
TypeError: Cannot read properties of undefined (reading 'total_layer')

    at i (http://home/_next/static/chunks/6021.60df47b592107a14.js:1:1145)
    at h (http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:35344)
    at n (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)
    at L (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:28970)
    at div
    at li
    at M (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:32852)
    at ul
    at J (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:36863)
    at div
    at http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:44035
    at div
    at l (http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:70166)
    at http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:62780
    at http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:61725
    at l (http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:70166)
    at http://home/_next/static/chunks/6133-1abb682bd7f256a6.js:1:41981
    at div
    at U (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:37258)
    at div
    at div
    at he (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:54675)
    at n (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:15358)
    at http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588
    at fe (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:52681)
    at div
    at div
    at div
    at pe (http://home/_next/static/chunks/pages/index-d5b31e72408b9b32.js:1:62156)
    at a (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15657)
    at a (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:15300)
    at s (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:16216)
    at u (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:14728)
    at http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:89588
    at http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:13979
    at l (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:1471)
    at n (http://home/_next/static/chunks/pages/_app-ea382104d33a6f0d.js:1:6048)
    at r (http://home/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (http://home/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (http://home/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)
```

### Steps to reproduce

1. Setup Moonraker Widget using default info
2. view page
3.

### homepage version

v0.8.3 (44b7de7, Dec 10, 2023)

### Installation method

Docker

### Configuration

```yaml
- Fun:
    - 3D Printer:
        href: http://10.1.10.55/
        description: Elegoo Neptune 4
        icon: fluidd.png
        widget:
            type: moonraker
            url: http://10.1.10.55
```
```


### Container Logs

_No response_

### Browser Logs

![image](https://github.com/gethomepage/homepage/assets/1133401/9c3d908a-06cf-46bd-ba9a-e02813b9557c)


### Troubleshooting

1. Config doesnt end in / for that url
2. Ping works, avg response of 3 ms
3. Output of http://PRINTER_IP/printer/objects/query?print_stats
```
{"result": {"status": {"print_stats": {"print_duration": 0.0, "total_duration": 0.0, "filament_used": 0.0, "filename": "", "state": "standby", "message": ""}}, "eventtime": 195.832628592}}
```


### Other

_No response_

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Do you know why your moonraker isn’t outputting any of expected data eg `result.status.print_stats.info.total_layer`

Like, that output you included above looks kinda useless, no? 0.0, empty strings, is that normal?

**Comment by slamanna212** [comment]
I just did not have anything printing when I submitted the bug report, here is its current output and a screenshot of fluidd from around the same time

{"result": {"status": {"print_stats": {"print_duration": 13200.186929045, "total_duration": 13299.968820801, "filament_used": 9341.571829999999, "filename": "AWDock.gcode", "state": "printing", "message": ""}}, "eventtime": 14811.486847187}}

![image](https://github.com/gethomepage/homepage/assets/1133401/a0a1e556-33aa-4dc3-9230-0133ab9f84b3)

**Comment by shamoon** [comment]
How about the other 2 endpoints when it's not printing? `display_status` and `webhooks`?

**Comment by slamanna212** [comment]
Once this print finishes in a little over an hour I'll post those here! This is my third attempt at this print and so far so good!

**Comment by slamanna212** [comment]
` http://10.1.10.55/printer/objects/query?display_status `

`{"result": {"status": {"display_status": {"progress": 0.0, "message": "Printing"}}, "eventtime": 20286.194312672}}`

`http://10.1.10.55/printer/objects/query?webhooks`

`{"result": {"status": {"webhooks": {"state": "ready", "state_message": "Printer is ready"}}, "eventtime": 20345.362690034}}`
