### ISSUE TITLE
[Bug] HTTPS for Omada widget not functional?

### ISSUE THREAD

**Issue by dKatsuro** [gethomepage/homepage#2545]
### Description

Attempted to add my remote Omada controller to Homepage but it seems like it doesn't like HTTPS.

### Steps to reproduce

1. Have a remote Omada instance with HTTPS only?
2. Attempt to add into services.yaml.
3. Watch it fail?

### homepage version

v0.8.4 (32f28d3, Dec 26, 2023)

### Installation method

Docker

### Configuration

```yaml
- Network:
    - Omada:
        widget:
          type: omada
          url: https://omada.redacted.com:443
          username: api
          password: redacted
          site: redacted
```

### Container Logs

```
[2023-12-30T17:29:32.165Z] error: <httpProxy> Error calling http://omada.redacted.com/b0f51984dd4412071f395605311a69c8/api/v2/sites...
[2023-12-30T17:29:32.166Z] error: undefined
[2023-12-30T17:29:32.166Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:462:24)
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
      ... 3 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:284:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:459:10)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:62:10)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2023-12-30T17:30:30.761Z] error: undefined
[2023-12-30T17:30:31.703Z] error: undefined
```

### Browser Logs

![image](https://github.com/gethomepage/homepage/assets/45524735/6f0f2aba-fd1d-4ca5-8d4a-5718c41d1854)

### Troubleshooting

I verified I could communicate with the Omada api via terminal within the container via https and didn't encounter any issues there.

Connect to container.

```
docker exec -ti homepage sh
```
Installed curl and jq for steps below..

```
# set variables
OMADA_URL="https://omada.redacted.com:443"
USERNAME="api"
PASSWORD="redacted"

# get controller id from the API
CONTROLLER_ID="$(curl -sk "${OMADA_URL}/api/info" | jq -r .result.omadacId)"

# login, get token, set & use cookies
TOKEN="$(curl -sk -X POST -c "/tmp/omada-cookies.txt" -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/login" -d '{"username": "'"${USERNAME}"'", "password": "'"${PASSWORD}"'"}' | jq -r .result.token)"

# once logged in, make sure you add the following header on additional API calls:
# -H "Csrf-Token: ${TOKEN}"

# validate login
curl -sk -X GET -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" -H "Csrf-Token: ${TOKEN}" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/loginStatus?token=${TOKEN}" | jq .

# example to get info on the current user
curl -sk -X GET -b "/tmp/omada-cookies.txt" -H "Content-Type: application/json" -H "Csrf-Token: ${TOKEN}" "${OMADA_URL}/${CONTROLLER_ID}/api/v2/users/current?token=${TOKEN}&currentPage=1&currentPageSize=1000"
```

Successful response from API within the container:
```
{"errorCode":0,"msg":"Success.","result":{"id":"65905258abab756c19cab61d","type":0,"roleId":"viewer_id","roleName":"Viewer","name":"api","omadacId":"b0f51984dd4412071f395605311a69c8","privilege":{"sites":[{"name":"RedactedSiteName","category":"advanced","key":"65780ccaabab756c19528a17"}],"lastVisited":"65780ccaabab756c19528a17","lastSiteCategory":"advanced","all":false},"disaster":0,"needFeedback":true,"forceModify":false,"dbnormal":true,"view":0,"root":false,"userLevel":0}}
```

### Other

The Omada instance in question is not locally hosted on this machine but at a remote location and is behind Nginx Proxy Manager. When I did review the two other issues that were reported with similar issues I did see one was attempting to use https with the same error shown on the homepage site but they didn't include logs. But - another person with similar errors was also using http with the same issue, also without homepage logs.

Other Information:
Omada Controller v5.13.22
Nginx Proxy Manager v2.10.4

Nginx Proxy Manager settings:
![image](https://github.com/gethomepage/homepage/assets/45524735/80085733-8d95-403d-8166-ec59350f0033)
![image](https://github.com/gethomepage/homepage/assets/45524735/6dde6f9b-378a-4a83-8e7d-cab651eabda1)
Nothing in Advanced or Custom locations.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
I believe that means your Omada is actually redirecting to http, even if it's listening on https. As you see here, our httpProxy should use an https agent if the URL has that protocol

https://github.com/darnfish/homepage/blob/461ca5be3a4381912d7e5b370987a6c3ccc39677/src/utils/proxy/http.js#L87-L94

And looking at the logs `at Object.request (node:https:366:10)` I believe that is correctly happening. But as of https://github.com/gethomepage/homepage/releases/tag/v0.8.0 the app is more strict about what it accepts

Perhaps an issue in the RP or something between the two, but I dont think this is a bug in homepage.
