### ISSUE TITLE
[Bug] Docker container labels missing 'name' breaks dashboard

### ISSUE THREAD

**Issue by pendor** [gethomepage/homepage#2551]
### Description

When using Docker container labels to define services, if a container has any 'homepage.*' labels but is missing a 'homepage.name' label, it breaks the entire dashboard.  The missing .name attribute is accessed without check in the compareServices method which results in a 500 error to the /api/services endpoint (see logs below).

### Steps to reproduce

1. Configure Homepage to access Docker via dockerproxy.
2. Create a container with labels (see below under configuration) but missing the homepage.name label.
3. 'up' the container.
4. Homepage breaks completely until the container is destroyed or homepage.name label is added & container redeployed.

### homepage version

v0.8.4 (32f28d3, Dec 27, 2023)

### Installation method

Docker

### Configuration

```yaml
The following labels were present on a container:
labels:
      homepage.group: Networking
      homepage.href: https://myurl
      homepage.description: My Description
      homepage.icon: icon.png
```

### Container Logs

[2023-12-31T17:48:07.656Z] error: <index> TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at compareServices (/app/.next/server/pages/index.js:3348:24)
    at Array.sort (<anonymous>)
    at /app/.next/server/pages/index.js:3459:148
    at Array.forEach (<anonymous>)
    at servicesResponse (/app/.next/server/pages/index.js:3447:21)
    at async getStaticProps (/app/.next/server/pages/index.js:2846:22)
    at async Object.renderToHTML (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/render.js:386:20)
    at async doRender (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:796:28)
    at async /app/node_modules/.pnpm/next@12.3.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/response-cache/index.js:80:36
[2023-12-31T17:48:08.170Z] error: undefined

### Troubleshooting

n/a

### Other

In correct metadata on one container shouldn't be able to break the entire dashboard instance.  Error checking should catch the missing field before accessing it and provide an error or at least ignore the missing data gracefully and proceed with rendering the rest of the dashboard.

### Before submitting, I have made sure to

- [X] Check [the documentation](https://gethomepage.dev/)
- [X] Follow [the troubleshooting guide](https://gethomepage.dev/latest/more/troubleshooting/) (please include output above if applicable).
- [X] Search [existing issues](https://github.com/gethomepage/homepage/search?q=&type=issues) and [discussions](https://github.com/gethomepage/homepage/search?q=&type=discussions).

**Comment by shamoon** [comment]
Im not sure we really need to "fix" this, not having a name is in fact not valid. Its sorta like having an error in a yaml file, which breaks things, and Im kinda ok with that since its not likely intentional and wont work...

**Comment by shamoon** [comment]
As I said, not convinced we should but I went ahead and added more graceful handling of this. Now you'd get e.g.

```
[2023-12-31T18:42:44.497Z] error: <service-helpers> Error constructing service using homepage labels for container 'speedtest1'. Ensure required labels are present.
[2023-12-31T18:42
```
