### ISSUE TITLE
### Description

### ISSUE THREAD

**Issue by dalekirkwood** [gethomepage/homepage#4390]
Hello - i'd like to reopen this ticket as Office 365 is pretty popular. 

### Description

Following the guide here: https://gethomepage.dev/latest/widgets/services/calendar/#ical
I have set up a calendar using the iCal link from an Office365 Outlook account and also an iCal link from a Google calendar. The Google calendar works fine so I know it is set up correctly, but when using the O365 iCal link I get the following error:

```
Something went wrong.
Error: Unsupported RFC prop EXDATE in EXDATE;TZID=Pacific

    at g (http://homepage.gondor.local/_next/static/chunks/6357.f441a79dcc11779d.js:1:1874)
    at h (http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:35344)
    at div
    at div
    at div
    at c (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:2589)
    at M (http://homepage.gondor.local/_next/static/chunks/3594.a65089216dd6b11e.js:1:8090)
    at h (http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:35344)
    at n (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:15357)
    at L (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:29574)
    at div
    at li
    at H (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:33456)
    at ul
    at M (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:37529)
    at div
    at http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:44034
    at div
    at l (http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:70165)
    at http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:62779
    at http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:61724
    at l (http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:70165)
    at http://homepage.gondor.local/_next/static/chunks/3653-fed476251d1d86e9.js:1:41980
    at div
    at J (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:38025)
    at div
    at div
    at me (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:55439)
    at n (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:15357)
    at http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:90404
    at fe (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:53445)
    at div
    at div
    at div
    at pe (http://homepage.gondor.local/_next/static/chunks/pages/index-acb0ccbe544c46b8.js:1:62972)
    at a (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:16473)
    at a (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:16116)
    at s (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:17032)
    at u (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:15544)
    at http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:90404
    at http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:14795
    at l (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:1471)
    at n (http://homepage.gondor.local/_next/static/chunks/pages/_app-2dea00bbc8a088a3.js:1:6048)
    at r (http://homepage.gondor.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:6989)
    at Y (http://homepage.gondor.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:9236)
    at ie (http://homepage.gondor.local/_next/static/chunks/main-5004eaa7b9f962cb.js:1:11878)
```

### homepage version

v0.8.7 (05a7c0f)

### Installation method

Docker

### Configuration

```yaml
Using the ghcr.io/gethomepage/homepage:latest image running on a Raspberry Pi 3B+. Raspberry Pi is running Debian 12.
```

### Troubleshooting

I've confirmed a google calendar works, but I only have one O365 account I can test with so I have not tested multiple O365 accounts. My suspicion is it's possibly related to me working with multiple timezones and sharing reoccurring events with coworkers and customers that are in Pacific and Central timezones while I myself live in Eastern timezone.

_Originally posted by @noxiousnick in https://github.com/gethomepage/homepage/discussions/2831_

**Comment by dalekirkwood** [comment]
Just FYI - a workaround

Add the calendar to Google Cal 0 Add from URL
![image](https://github.com/user-attachments/assets/6d5610c2-f638-4d85-afcd-d532534ff6a0)

And make the calendar publicly accessible. Then use the public ICS link.

![image](https://github.com/user-attachments/assets/26843f8d-8b74-4667-919c-2f95e4253f01)
